config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do

  devise_for :users, path: '',
    path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
    controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }


  devise_scope :user do
    post '/sign_up', to: 'devise/registrations#create', as: :sign_up
  end


  get '/thank_you' => "static#thank_you"


  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  filter :locale, exclude: /\/auth\//

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount CatarsePaypalExpress::Engine => "/", as: :catarse_paypal_express
  mount CatarseMoip::Engine => "/", as: :catarse_moip

  # Channels
  constraints subdomain: /^(?!www|secure|test|local)(\w+)/ do
    namespace :channels, path: '' do
      namespace :admin do
        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end
        resources :followers, only: [ :index ]
        resources :projects, only: [ :index, :update] do
          member do
            put 'approve'
            put 'reject'
            put 'push_to_draft'
          end
        end
      end
      get '/', to: 'profiles#show', as: :profile
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resource :profile
      resources :projects, only: [:new, :create, :show] do
        collection do
          get 'video'
        end
      end
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, controller: 'projects/updates', only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end
    resources :backers, controller: 'projects/backers' do
      member do
        put 'credits_checkout'
      end
    end
    collection do
      get 'video'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
    end
  end
  resources :users do
    resources :projects, controller: 'users/projects', only: [ :index ]
    collection do
      get :uservoice_gadget
    end
    resources :backers, controller: 'users/backers', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :statistics, only: [ :index ]
    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
        put 'push_to_trash'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug
end

app/models/reward.rb
# coding: utf-8
class Reward < ActiveRecord::Base
  include RankedModel

  include ERB::Util
  schema_associations
  has_many :backers, dependent: :nullify

  ranks :row_order, with_same: :project_id
  has_paper_trail

  validates_presence_of :minimum_value, :description, :days_to_delivery
  validates_numericality_of :minimum_value, greater_than_or_equal_to: 10.00
  validates_numericality_of :maximum_backers, only_integer: true, greater_than: 0, allow_nil: true
  scope :remaining, -> { where("maximum_backers IS NULL OR (maximum_backers IS NOT NULL AND (SELECT COUNT(*) FROM backers WHERE state IN ('confirmed', 'waiting_confirmation') AND reward_id = rewards.id) < maximum_backers)") }
  scope :sort_asc, -> { order('id ASC') }

  delegate :display_deliver_prevision, :display_remaining, :name, :display_minimum, :short_description,
           :medium_description, :last_description, :display_description, to: :decorator
  def decorator
    @decorator ||= RewardDecorator.new(self)
  end

  def has_modification?
    versions.count > 1
  end

  def sold_out?
    maximum_backers && total_compromised >= maximum_backers
  end

  def total_compromised
    backers.with_states(['confirmed', 'waiting_confirmation']).count
  end

  def remaining
    return nil unless maximum_backers
    maximum_backers - total_compromised
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  load_and_authorize_resource
  inherit_resources
  belongs_to :project
  respond_to :html, :json

  def index
    render layout: false
  end

  def new
    render layout: false
  end

  def edit
    render layout: false
  end

  def update
    update!(notice: t('projects.update.success')) { project_by_slug_path(permalink: parent.permalink) }
  end

  def create
    create!(notice: t('projects.update.success')) { project_by_slug_path(permalink: parent.permalink) }
  end

  def destroy
    destroy! { project_by_slug_path(permalink: resource.project.permalink) }
  end

  def sort
    resource.update_attribute :row_order_position, params[:reward][:row_order_position]

    render nothing: true
  end
end

app/views/rewards/_form.html.slim
= semantic_form_for [parent, resource], html: { class: 'remote-form' } do |f|
  - if resource.new_record? || can?(:update, resource, :minimum_value)
    = f.input :minimum_value, required: true, as: :number, input_html: {pattern: "^[\\d+.]+"}

  - if resource.new_record? || can?(:update, resource, :days_to_delivery)
    = f.input :days_to_delivery, required: true

  - if resource.new_record? || can?(:update, resource, :description)
    = f.input :description, required: true

  - if resource.new_record? || can?(:update, resource, :maximum_backers)
    = f.input :maximum_backers

  .clearfix
  = f.submit class: 'btn', disable_with: I18n.t('sending')
  - if resource.persisted? && can?(:destroy, resource)
    br/
    = link_to [parent, resource], class: 'btn btn-danger', method: :delete, confirm: 'Are you sure?' do
      i.icon-trash.icon-white

app/views/rewards/edit.html.slim
= render 'form'

app/views/rewards/index.html.slim
- collection.rank(:row_order).each do |reward|

  /- if can?(:update, reward)
    .bootstrap-twitter.bootstrap-form
      .skull-modal.hide id="reward#{reward.id}Editor"
        .skull-modal-header
          h3= t('projects.rewards.edit_reward')
          a class='skull-modal-close' href='javascript:void(0);' &times;
        .skull-modal-body
          = image_tag 'loading.gif'


  div[id="reward_#{reward.id}" data-new_backer_url=new_project_backer_path(parent, reward_id: reward.id) data-update_url=sort_project_reward_path(parent, reward) class="box #{(can?(:update, reward) ? 'clickable_owner sortable' : '')} #{(parent.online? && !reward.sold_out? && !can?(:update, reward)  ? 'clickable'  : '' )}"]
    - if can?(:update, reward)

      .bootstrap-form.bootstrap-twitter 
        .hide id="reward#{reward.id}Editor"
          = image_tag 'loading.gif'

        .bootstrap-twitter
          = link_to "javascript:void(0);", data: {target: "#reward#{reward.id}Editor", path: edit_project_reward_path(@project, reward)}, class: 'show_reward_form btn btn-mini pull-right btn-primary' do
            i.icon-pencil.icon-white

    h2= t('projects.rewards.reward_title', minimum: reward.display_minimum).html_safe
    em= pluralize(reward.backers.with_state('confirmed').count, t('backer_singular'), t('backer_plural'))
    .clearfix
    p
      = reward.display_description
    - if reward.maximum_backers
      .maximum_backers.clearfix
        - if reward.sold_out?
          .sold_out= t('reward.sold_out')
        - else
          .limited= t('reward.limited')
          .remaining
            = reward.display_remaining
      - in_time_to_confirm = reward.backers.with_state('waiting_confirmation').count
      - if in_time_to_confirm > 0
        .maximum_backers.in_time_to_confirm.clearfix
          .pending= t('projects.rewards.backs_to_confirm', count: in_time_to_confirm)
      .clearfix
    - if reward.days_to_delivery.present?
      div class="reward_deliver_at"
        p= "#{t('projects.rewards.reward_deliver_time', prevision: reward.display_deliver_prevision)}".html_safe
    - if current_user && current_user.admin
      div class="reward_updated_at"
        p= "Modificado em: #{I18n.l(reward.updated_at.to_date)} #{parent.online_date.nil? ? '' : ((parent.online_date > reward.updated_at)? '(draft)' : '(online)')}"
      - if reward.has_modification?
        div class="description_version rewardVersioning#{reward.id}"
          p= reward.last_description
        .maximum_backers.in_time_to_confirm.clearfix
          .updated_reward
            span id="rewardVersioning#{reward.id}"
              = 'Veja a versão anterior.'
.clearfix

app/views/rewards/new.html.slim
= render 'form'