config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do

  devise_for :users, path: '',
    path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
    controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }


  devise_scope :user do
    post '/sign_up', to: 'devise/registrations#create', as: :sign_up
  end


  get '/thank_you' => "static#thank_you"


  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  filter :locale, exclude: /\/auth\//

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount CatarsePaypalExpress::Engine => "/", as: :catarse_paypal_express
  mount CatarseMoip::Engine => "/", as: :catarse_moip

  # Channels
  constraints subdomain: /^(?!www|secure|test|local)(\w+)/ do
    namespace :channels, path: '' do
      namespace :admin do
        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end
        resources :followers, only: [ :index ]
        resources :projects, only: [ :index, :update] do
          member do
            put 'approve'
            put 'reject'
            put 'push_to_draft'
          end
        end
      end
      get '/', to: 'profiles#show', as: :profile
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resource :profile
      resources :projects, only: [:new, :create, :show] do
        collection do
          get 'video'
        end
      end
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, controller: 'projects/updates', only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end
    resources :backers, controller: 'projects/backers' do
      member do
        put 'credits_checkout'
      end
    end
    collection do
      get 'video'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
    end
  end
  resources :users do
    resources :projects, controller: 'users/projects', only: [ :index ]
    collection do
      get :uservoice_gadget
    end
    resources :backers, controller: 'users/backers', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :statistics, only: [ :index ]
    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
        put 'push_to_trash'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug
end

app/models/concerns/backer/custom_validators.rb
module Backer::CustomValidators
  extend ActiveSupport::Concern

  included do
    validate :reward_must_be_from_project
    validate :value_must_be_at_least_rewards_value
    validate :should_not_back_if_maximum_backers_been_reached, on: :create
    validate :project_should_be_online, on: :create

    def reward_must_be_from_project
      return unless reward
      errors.add(:reward, I18n.t('backer.reward_must_be_from_project')) unless reward.project == project
    end

    def value_must_be_at_least_rewards_value
      return unless reward
      errors.add(:value, I18n.t('backer.value_must_be_at_least_rewards_value', minimum_value: reward.display_minimum)) unless value.to_f >= reward.minimum_value
    end

    def should_not_back_if_maximum_backers_been_reached
      return unless reward && reward.maximum_backers && reward.maximum_backers > 0
      errors.add(:reward, I18n.t('backer.should_not_back_if_maximum_backers_been_reached')) if reward.sold_out?
    end

    def project_should_be_online
      return if project && project.online?
      errors.add(:project, I18n.t('backer.project_should_be_online'))
    end

  end
end

app/models/concerns/backer/payment_engine_handler.rb
module Backer::PaymentEngineHandler
  extend ActiveSupport::Concern

  included do

    def payment_engine
      PaymentEngines.find_engine(self.payment_method) rescue nil
    end

    [:review_path, :refund_path].each do |method_name|
      define_method method_name do
        if payment_engine
          payment_engine[method_name].try(:call, self)
        end
      end
    end

  end
end

app/models/concerns/project/custom_validators.rb
module Project::CustomValidators
  extend ActiveSupport::Concern

  included do
    validate :permalink_cant_be_route, allow_nil: true

    def self.permalink_on_routes?(permalink)
      permalink && self.get_routes.include?(permalink.downcase)
    end

    def permalink_cant_be_route
      errors.add(:permalink, I18n.t("activerecord.errors.models.project.attributes.permalink.invalid")) if Project.permalink_on_routes?(permalink)
    end
  end
end

app/models/concerns/project/video_handler.rb
module Project::VideoHandler
  extend ActiveSupport::Concern

  included do
    mount_uploader :video_thumbnail, ProjectUploader

    delegate :display_video_embed_url, to: :decorator

    def video
      @video ||= VideoInfo.get(self.video_url) if self.video_url.present?
    end

    def download_video_thumbnail
      self.video_thumbnail = open(self.video.thumbnail_large)  if self.video_valid?
      self.save
    rescue OpenURI::HTTPError, TypeError => e
      Rails.logger.info "-----> #{e.inspect}"
    end

    def update_video_embed_url
      self.video_embed_url = self.video.embed_url if self.video_valid?
      self.save
    end

    def video_valid?
      self.video_url.present? && self.video
    end
  end
end

app/controllers/admin/backers_controller.rb
class Admin::BackersController < Admin::BaseController
  add_to_menu "admin.backers.index.menu", :admin_backers_path
  has_scope :by_user_id, :by_key, :user_name_contains, :user_email_contains, :payer_email_contains, :project_name_contains, :confirmed, :credits, :with_state, :by_value
  has_scope :between_values, using: [ :start_at, :ends_at ], allow_blank: true
  before_filter :set_title

  def self.backer_actions
    %w[confirm pendent refund hide cancel push_to_trash].each do |action|
      define_method action do
        resource.send(action)
        flash[:notice] = I18n.t("admin.backers.messages.successful.#{action}")
        redirect_to admin_backers_path(params[:local_params])
      end
    end
  end
  backer_actions

  def change_reward
    resource.change_reward! params[:reward_id]
    flash[:notice] = I18n.t('admin.backers.messages.successful.change_reward')
    redirect_to admin_backers_path(params[:local_params])
  end

  protected
  def set_title
    @title = t("admin.backers.index.title")
  end

  def collection
    @backers = apply_scopes(end_of_association_chain).without_state('deleted').order("backers.created_at DESC").page(params[:page])
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'
  add_to_menu "admin.projects.index.menu", :admin_projects_path

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
  has_scope :between_created_at, :between_expires_at, :between_online_date, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash!
    end

    redirect_to admin_projects_path
  end

  protected
  def collection
    @scoped_projects = apply_scopes(end_of_association_chain).with_project_totals.without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/channels/admin/projects_controller.rb
class Channels::Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'
  has_scope :by_id, :pg_search, :user_name_contains, :order_by, :with_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true

  before_filter do
    @total_projects =  channel.projects.size
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project    = channel.projects.find(params[:id])
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  protected
  def begin_of_association_chain
    channel
  end

  def collection
    @projects = apply_scopes(channel.projects.page(params[:page]))
  end
end

app/controllers/channels/projects_controller.rb
class Channels::ProjectsController < ProjectsController
  layout 'catarse_bootstrap'
  belongs_to :channel, finder: :find_by_permalink!, param: :profile_id


  # Inheriting from the original Projects controller
  # With one addition: we include the project into the current channel
  before_filter only: [:create] { params[:project][:channels] = [@channel] }

  prepend_before_filter{ params[:profile_id] = request.subdomain }
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update, :review, :create, :credits_checkout
  skip_before_filter :force_http, only: [:create, :edit, :update, :credits_checkout]
  skip_before_filter :verify_authenticity_token, only: [:moip]
  has_scope :available_to_count, type: :boolean
  has_scope :with_state
  has_scope :page, default: 1
  load_and_authorize_resource except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  def update
    resource.update_attributes(params[:backer])
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def index
    render collection
  end

  def show
    @title = t('projects.backers.show.title')
  end

  def new
    unless parent.online?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @create_url = ::Configuration[:secure_review_host] ?
      project_backers_url(@project, {host: ::Configuration[:secure_review_host], protocol: 'https'}) :
      project_backers_path(@project)

    @title = t('projects.backers.new.title', name: @project.name)
    @backer = @project.backers.new(user: current_user)
    empty_reward = Reward.new(minimum_value: 0, description: t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)

    # Select
    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @backer.reward = @selected_reward
      @backer.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.backers.create.title')
    @backer.user = current_user
    @backer.reward_id = nil if params[:backer][:reward_id].to_i == 0
    create! do |success,failure|
      failure.html do
        flash[:failure] = t('projects.backers.review.error')
        return redirect_to new_project_backer_path(@project)
      end
      success.html do
        resource.update_current_billing_info
        flash[:notice] = nil
        session[:thank_you_backer_id] = @backer.id
        return redirect_to edit_project_backer_path(project_id: @project.id, id: @backer.id)
      end
    end
    @thank_you_id = @project.id
  end

  def credits_checkout
    if current_user.credits < @backer.value
      flash[:failure] = t('projects.backers.checkout.no_credits')
      return redirect_to new_project_backer_path(@backer.project)
    end

    unless @backer.confirmed?
      @backer.update_attributes({ payment_method: 'Credits' })
      @backer.confirm!
    end
    flash[:success] = t('projects.backers.checkout.success')
    redirect_to project_backer_path(project_id: parent.id, id: resource.id)
  end

  protected
  def collection
    @backers ||= apply_scopes(end_of_association_chain).available_to_display.order("confirmed_at DESC").per(10)
  end
end

app/controllers/projects/updates_controller.rb
class Projects::UpdatesController < ApplicationController
  inherit_resources
  load_and_authorize_resource

  actions :index, :create, :destroy
  belongs_to :project

  def show
    render resource
  end

  def index
    render collection.page(params[:page]).per(3)
  end

  def create
    @update = parent.updates.create(params[:update].merge!(user: current_user))
    render @update
  end

  def destroy
    destroy!{|format| return index }
  end

  def collection
    @updates ||= end_of_association_chain.visible_to(current_user)
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  load_and_authorize_resource only: [ :new, :create, :update, :destroy, :send_to_analysis ]
  inherit_resources
  has_scope :pg_search, :by_category_id, :near_of
  has_scope :recent, :expiring, :successful, :recommended, :not_expired, type: :boolean

  respond_to :html
  respond_to :json, only: [:index, :show, :update]

  def index
    index! do |format|
      format.html do
        if request.xhr?
          @projects = apply_scopes(Project).visible.order_for_search.includes(:project_total, :user, :category).page(params[:page]).per(6)
          return render partial: 'project', collection: @projects, layout: false
        else
          @title = t("site.title")
          if current_user && current_user.recommended_projects.present?
            @recommends = current_user.recommended_projects.limit(3)
          else
            @recommends = ProjectsForHome.recommends
          end

          @channel_projects = Project.from_channels([1]).order_for_search.limit(3)
          @projects_near = Project.with_state('online').near_of(current_user.address_state).order("random()").limit(3) if current_user
          @expiring = ProjectsForHome.expiring
          @recent   = ProjectsForHome.recents
        end
      end
    end
  end

  def new
    new! do
      @title = t('projects.new.title')
      @project.rewards.build
    end
  end

  def create
    @project = current_user.projects.new(params[:project])

    create! { project_by_slug_path(@project.permalink) }
  end

  def send_to_analysis
    resource.send_to_analysis
    flash[:notice] = t('projects.send_to_analysis')
    redirect_to project_by_slug_path(@project.permalink)
  end

  def update
    update!(notice: t('projects.update.success')) { project_by_slug_path(@project.permalink, anchor: 'edit') }
  end

  def show
    @title = resource.name
    fb_admins_add(resource.user.facebook_id) if resource.user.facebook_id
    @updates_count = resource.updates.count
    @update = resource.updates.where(id: params[:update_id]).first if params[:update_id].present?
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  rescue VideoInfo::UrlError
    render json: nil
  end

  %w(embed video_embed).each do |method_name|
    define_method method_name do
      @title = resource.name
      render layout: 'embed'
    end
  end

  def embed_panel
    @title = resource.name
    render layout: false
  end

  protected

  def resource
    @project ||= (params[:permalink].present? ? Project.by_permalink(params[:permalink]).first! : Project.find(params[:id]))
  end
end

app/controllers/users/backers_controller.rb
class Users::BackersController < ApplicationController
  inherit_resources
  defaults resource_class: Backer, collection_name: 'backs', instance_name: 'back'
  belongs_to :user
  actions :index

  def index
    render layout: false
  end

  def request_refund
    authorize! :request_refund, resource
    if resource.value > resource.user.user_total.credits
      flash[:failure] = I18n.t('credits.index.insufficient_credits')
    elsif can?(:request_refund, resource) && resource.can_request_refund?
      resource.request_refund!
      flash[:notice] = I18n.t('credits.index.refunded')
    end

    redirect_to user_path(parent, anchor: 'credits')
  end

  protected
  def collection
    @backs = end_of_association_chain.available_to_display.order("created_at DESC, confirmed_at DESC")
    @backs = @backs.not_anonymous.with_state('confirmed') unless can? :manage, @user
    @backs = @backs.includes(:user, :reward, project: [:user, :category, :project_total]).page(params[:page]).per(10)
  end
end

app/controllers/users/projects_controller.rb
class Users::ProjectsController < ApplicationController
  inherit_resources
  actions :index
  belongs_to :user

  def index
    render layout: false
  end

  def collection
    @projects ||= end_of_association_chain.page(params[:page]).per(10)
  end
end

app/views/projects/backers/_anonymous_warning.en.html.slim
strong Are you sure you want your back to be anonymous? 
| Leaving your back public gives you a better reputation and count points on our ranking of backers.
br
br
| Besides that, the amount you backed will never be disclosed to no one but the project owner (who will always know who you are), even if your back is public.

app/views/projects/backers/_anonymous_warning.pt.html.slim
strong Você tem certeza que quer que seu apoio seja anônimo? 
| Deixar seu apoio público aumenta sua reputação e conta pontos para o nosso ranking de apoiadores.
br
br
| Além disso, o valor do seu apoio não será divulgado para ninguém além do dono do projeto. Somente o proponente terá acesso a essa informação, independente se o seu investimento seja público ou anônimo.

app/views/projects/backers/_back_text.en.html.slim
h2 I want to back, what’s next?
h3 How can I back this project?
p First, define the value of your contribution and choose a reward. Then click on “Review and make a payment”  to redirect you to the next page to complete your payment.
h3 When payment is effected?
p Once the MoIP or Paypal confirm the transaction (card and bank transfer confirmation is on the same day, lead slips to 4 working days to be confirmed). Then, if the project does not reach #{@project.display_goal} by #{@project.display_expires_at}, you will receive your money back in the form of credits on #{Configuration[:company_name]}.
h3 Then I get my money back if the project does not go out?
p Yes! You receive back 100% of what you paid in the form of credits to support other projects on #{Configuration[:company_name]}.
h3 And if I do not want to use the credits in #{Configuration[:company_name]}?
p No problem. Just enter the #{link_to t('credits.title'), user_path(current_user, anchor: :credits), :target => :_blank} tab, 60 days after their support and request a chargeback. If you have paid by credit card, the reversal will be done on your next bill. If you paid with debit or bank, the only way to do the chargeback is you open an account on MoIP. Then we transfer the value of our account to yours and from there you transfer to your bank account.
h3 If the project is funded, how do I get my reward?
p When your reward is ready, #{link_to @project.user.display_name, user_path(@project.user)} will contact you to arrange delivery.

app/views/projects/backers/_back_text.pt.html.slim
h2 Quero apoiar, e agora?
h3 Como eu apoio este projeto?
p Primeiro, escolha o valor e a recompensa desejados. Depois é só clicar em 'Revisar e realizar pagamento' que redirecionaremos você para a próxima página para concluir o seu pagamento.
h3 Quando o pagamento é efetivado?
p Assim que o MoIP ou o Paypal confirmar a transação (cartão e transferência bancária a confirmação é no mesmo dia, boletos levam até 4 dias úteis para serem confirmados). Depois, caso o projeto não atinja #{@project.display_goal} até #{@project.display_expires_at}, você receberá seu dinheiro de volta na forma de créditos no #{Configuration[:company_name]}.
h3 Então eu recebo meu dinheiro de volta se o projeto não sair?
p Sim! Você recebe de volta 100% do que pagou na forma de créditos para apoiar outros projetos do #{Configuration[:company_name]}.
h3 E se eu não quiser usar os créditos no #{Configuration[:company_name]}?
p Sem problemas. É só entrar na aba #{link_to t('credits.title'), user_path(current_user, anchor: :credits), :target => :_blank}, até 60 dias após seu apoio, e solicitar um estorno. Caso tenha pago com cartão de crédito, o estorno será feito na sua próxima fatura. Se pagou com débito em conta ou boleto bancário, a única maneira de fazer o estorno é você abrir uma conta no MoIP. Aí a gente transfere o valor da nossa conta para a sua e, de lá, você transfere para sua conta no banco.
h3 Se o projeto for financiado, como eu recebo minha recompensa?
p Quando sua recompensa estiver pronta, #{link_to @project.user.display_name, user_path(@project.user)} vai entrar em contato com você para combinar a entrega.

app/views/projects/backers/_backer.html.slim
.backer
  - if backer.anonymous
    img src="/assets/user.png" class="backer_avatar"
    .back_info
      p#text
        em.anon=" #{t('.anonymous_backer')}"
      p#confirmed
        = backer.confirmed_at
      p#backed= t('.anonymous_description')
  - else
    a href=user_path(backer.user)
      img src=backer.user.display_image class="backer_avatar"
    .back_info
      p#text
        a href=user_path(backer.user)
         = backer.user.short_name
      p#confirmed
        = backer.confirmed? ? backer.confirmed_at : backer.created_at
      p#backed
        = backer.user.backs_text
  - if current_user and (current_user == @project.user or current_user.admin)
    .reward
      =
      .value = backer.value
      - if backer.reward
        .user_reward
          = backer.reward.display_minimum
          |  -
          = backer.reward.medium_description
      - else
        | &nbsp;
        = t('.no_reward')
      - if backer.user.email
        .user_email = backer.user.email
      - else
        | &nbsp;
        = t('not_informed')
      |.

  .clear

app/views/projects/backers/edit.html.slim
#page_content
  .container
    #project_review data-thank-you-path=project_backer_path(project_id: @project.id, id: @backer.id)
      .project_info
        = image_tag @project.display_image, id: 'project_image', alt: @project.name, width: '250px'
        h1= t('.you_are_about_html', link: link_to(@project.name, project_by_slug_path(permalink: @project.permalink)))
        #review_text
          - if @backer.reward
            .review_content
              = t('.review_with_reward_html', value: @backer.display_value)
            .reward
              = @backer.reward.description
          - else
            .review_content
              = t('.review_without_reward_html', value: @backer.display_value)
      .clearfix
      .title
        h1= t('.title')
        h2= t('.subtitle')
      .clearfix
      - if @backer.credits
        #back_with_credits
          .bootstrap-alert
            .alert
              #credits_notice= t('.credits_notice_html', credits: number_to_currency((current_user.credits - @backer.value), unit: 'R$', precision: 0, delimiter: '.'))
      .bootstrap-form
        = semantic_form_for current_user, url: credits_checkout_project_backer_path(@backer.project, @backer), html: { data: { update_info_path: project_backer_path(project_id: @backer.project.id, id: @backer.id, format: :json) }, id: 'review_form', class: "form-horizontal #{('dont_align' if @backer.credits)}", method: 'put' } do |form|
          = hidden_field_tag 'project_id', @backer.project.id
          = hidden_field_tag 'backer_id', @backer.id
          = hidden_field_tag 'backer_credits', @backer.credits
          = hidden_field_tag 'payment_method_url', nil
          - unless @backer.credits
            = form.inputs do
              fieldset.live_in_brazil
                = check_box_tag 'live_in_brazil', 'live', params[:locale] == 'pt'
                = label_tag 'live_in_brazil', t('.live_in_brazil'), class: 'inline'
              = form.input :full_name, required: true, as: :string
              /= form.input :cpf, as: :string, input_html: {autocomplete: 'off'}
              = form.input :email, required: true, as: :string
              .clearfix
              fieldset.address_data
                .title
                  h2
                = form.input :address_street, as: :string, required: true
                = form.input :address_number, as: :string, required: true
                = form.input :address_complement, required: false, as: :string
                = form.input :address_neighbourhood, as: :string, required: true
                = form.input :address_zip_code, as: :string, input_html: {autocomplete: 'off', data: {mask: '99999-999'}}, required: true
                = form.input :address_city, as: :string, required: true
                = form.input :address_state, as: :select, collection: State.array, required: true
                = form.input :phone_number, as: :string, input_html: {autocomplete: 'off', data: {mask: '(99)9999-9999?9'}}, required: true
          .submit
            fieldset.accept_terms
              = check_box_tag 'accept'
              = label_tag 'accept', t('accept_terms_html', link: link_to(t('terms'), ::Configuration[:terms_url], target: :_blank)), class: 'inline'
            - if @backer.credits
              = form.actions do
                .bootstrap-twitter
                  = form.submit (@backer.credits ? t('.submit.credits') : t('.submit.moip')), class: 'btn', id: 'user_submit'

        - unless @backer.credits
          #payment.hide data-update-info-path=project_backer_path(project_id: @backer.project.id, id: @backer.id, format: :json)
            .title
              h1= t('.choose_payment')
              h2= t('.choose_payment_subtitle')

            .tab_container
              nav#payment_menu
                - PaymentEngines.engines.each do |engine|
                  = link_to "##{engine[:name]}_payment", id: engine[:name], class: 'selected enabled' , data: {target: "##{engine[:name]}_payment"} do
                    = t("projects.backers.review.#{engine[:name]}")
            .tab_content_container
              - PaymentEngines.engines.each do |engine|
                div[id="#{engine[:name]}_payment" class="payments_type hide" data-path=engine[:review_path].call(@backer) ]
    .clearfix

app/views/projects/backers/new.html.slim
#page_content
  .container
    .backer_content
      .title
        h1= t('.header.title')
        h2= t('.header.subtitle')
      #back_options.bootstrap-form
        = semantic_form_for @backer, url: @create_url, html: { id: 'backer_form' } do |form|
          = form.inputs do
            = hidden_field_tag 'credits', current_user.credits.to_i
            = form.input :referal_link, as: :hidden, input_html: { value: referal_link }
            = form.label :value, t('formtastic.labels.backer.value')
            - if current_user.credits >= 10
              .bootstrap-alert
                .alert.alert-info
                  = form.input :credits, hint: t('formtastic.hints.backer.credits', credits: current_user.display_credits).html_safe
              .clearfix
            = form.input :value, required: true, as: :string, label: false,  input_html: { pattern: '\\d+', autocomplete: 'off', data: { rewards: @rewards.map{|r| {id: r.id, minimum_value: r.minimum_value.to_i} }.to_json } }
            .simbol
              p R$
            = form.input :reward, as: :radio, collection: @rewards
            = form.input :anonymous
            li#anonymous_warning.important.hide
              .bootstrap-alert
                .alert
                  = render 'anonymous_warning'
          = form.actions do
            .bootstrap-twitter
              = form.submit t('.submit'), class: 'btn btn-primary btn-large', id: "backer_submit"
      #back_info
        #project_info
          .project_name= link_to @project.name, project_by_slug_path(permalink: @project.permalink)
          = image_tag @project.display_image, alt: @project.name, class: 'project_image', width: 280
          .project_owner por #{link_to @project.user.display_name, user_path(@project.user)}
          .project_expires_at #{@project.time_to_go[:time]} #{@project.time_to_go[:unit]} #{pluralize_without_number(@project.time_to_go[:time], t('remaining_singular'), t('remaining_plural'))}
        .clearfix
        .back_faq
          = render 'back_text'
      .clearfix
    .clearfix

app/views/projects/backers/show.html.slim
#page_content
  .container
    #thank_you
      .title
        h1 = t('.header_title')
        h2= t('.header_subtitle')
      .project_info
        = image_tag @project.display_image, id: 'project_image', alt: @project.name, width: '250px'
        h1= t('.text_title_html', link: link_to(@project.name, project_by_slug_path(permalink: @project.permalink)))
        #review_text
          - if @backer.payment_method == 'MoIP' && @backer.payment_id
            = t('.moip_message', code: @backer.payment_id).html_safe
            br
            br
          = t("projects.back_project.display_status.#{@project.display_status}", goal: @project.display_goal, date: @project.display_expires_at)
        .share
            h2= t('.text_subtitle')
            = link_to "http://twitter.com/?status=#{t('i_just_backed', name: @project.name)} #{project_by_slug_url(permalink: @project.permalink)}", target: :_blank do
              = image_tag 'catarse/icon-tw.png', title: 'Twitter'
            = link_to "http://www.facebook.com/share.php?u=#{project_by_slug_url(permalink: @project.permalink)}", target: :_blank do
              = image_tag 'catarse/icon-fb.png', title: 'Facebook'
        #recommended_projects
          h2 = t('.recommended_projects')
          - @backer.recommended_projects.limit(3).each do |project|
            = render partial: 'projects/project', locals: {project: project }
      .clearfix